Introducing Box-Muller Transform for Generating Random Numbers
husxk/pwr-niduc-p pull request #3
Opened 2024-04-02 15:18 UTC by misiektest

2024-04-02 16:58 UTC, kornelu123 reviewed
Looks decent, few comments though

2024-04-02 16:58 UTC, kornelu123 commented on mt_rng.cpp
> +double get_normal(double mu, double sigma)
What does mu stands for ?

2024-04-02 16:58 UTC, kornelu123 commented on mt_rng.cpp
> +double get_normal(double mu, double sigma)
Why does this function returns double ? Don't we want it to return uint32_t with normal distribution ?

2024-04-02 22:27 UTC, kornelu123 commented
Also, @misiektest @husxk can we move this from .xpp to .x ? I would like to include it in my C code, and the fact that this file is a C++ file forbids me from using .c not .cpp file extension. This code does not have any c++ exclusive library, so it doesn't make a difference.

2024-04-03 13:57 UTC, misiektest commented on mt_rng.cpp
> +double get_normal(double mu, double sigma)
Alright. Let's cast it.

2024-04-03 13:58 UTC, misiektest commented on mt_rng.cpp
> +double get_normal(double mu, double sigma)
I will make the variables more descriptive

2024-04-03 14:15 UTC, misiektest commented
If it's necessary we can move to C. It would require some refactoring from my side as I've used some cpp syntactic sugar already, like static casting and constexpr but it's not that much work to do. Anyway if it helps you we can do that. What is your opinion @husxk?

2024-04-03 20:22 UTC, kornelu123 commented
Also, we want 1 commit, no 'Applying suggestions' ones. Also we need this code with some proof that it's distribution is normal for next meet with ironman.

2024-04-03 21:59 UTC, husxk commented
It would be nice if you provide to this project some small python utility script to draw a plot using generated random numbers from this code (to see if it is normal distribution).
It would be implemented in another commit (it would be nice if it is implemented in the same PR), and another directory (for instance `pwr-niduc-p/scripts` or other appropriate name)

2024-04-03 22:12 UTC, husxk commented
> Also, @misiektest @husxk can we move this from .xpp to .x ? I would like to include it in my C code, and the fact that this file is a C++ file forbids me from using .c not .cpp file extension. This code does not have any c++ exclusive library, so it doesn't make a difference.

I think we shouldn't change extension to *.c, it is C++ project. We are using constexpr and std::isnan from C++.

Why do you need to use C here? Is your code, that you had mentioned, for this particular project?

2024-04-03 22:21 UTC, kornelu123 commented
nvm, leave it as it is.

2024-04-04 09:54 UTC, misiektest commented
> It would be nice if you provide to this project some small python utility script to draw a plot using generated random numbers from this code (to see if it is normal distribution). It would be implemented in another commit (it would be nice if it is implemented in the same PR), and another directory (for instance `pwr-niduc-p/scripts` or other appropriate name)

![Figure_1](https://github.com/husxk/pwr-niduc-p/assets/95294593/2d3de465-9929-4cac-a3a1-6a79ab625751)
That's how it can look. But I don't like the way i got it. First a .cpp file to generate the data and write it to file. And small python script to generate the plot. Do you have any ideas how to better integrate the genration of data into project? I wouldn't go down the whole of integrating this project  just to create one plot. I'm not convinced that the costs justify the benefits.

2024-04-04 09:58 UTC, kornelu123 commented
You could just write to stdout at c++ site, and then read from stdin at python. Also there is a possibility of just using c++ functions inside of python script.

2024-04-04 09:59 UTC, kornelu123 commented
Also, could you also make a plot for mersenne_twister() function, without the normalisation ?

2024-04-04 10:03 UTC, kornelu123 commented
And please make the plot text font bigger. Also, y-axis title shouldn't be `frequency`.

2024-04-04 10:18 UTC, misiektest commented
> You could just write to stdout at c++ site, and then read from stdin at python. Also there is a possibility of just using c++ functions inside of python script.

I was getting deeper this morning and it's not that easy

2024-04-04 10:46 UTC, kornelu123 commented
And please make the plot text font bigger. Also, y-axis title shouldn't be `frequency`. Should i take care of this python script, or you got this?

2024-04-04 13:23 UTC, husxk commented on mt_rng.cpp
> +    //the method generates two values. In order not to drop the second value we store it.
Can you say explicitly in which variable we store the value? Just for clearness.

2024-04-04 13:23 UTC, husxk commented on mt_rng.hpp
>  uint32_t mersenne_twister();
Can we hide it from .hpp and make static function in .cpp?
I think we will be using `get_next()` and `get_normal()`.

2024-04-05 15:43 UTC, misiektest commented
![Figure_1](https://github.com/husxk/pwr-niduc-p/assets/95294593/1dc74a9f-68c3-418d-b93a-2b94e8b0c727)
![Figure_2](https://github.com/husxk/pwr-niduc-p/assets/95294593/44302841-4864-4710-a47a-5a69da889e31)
That' how it looks, values from get_next() and get_normal().

2024-04-09 09:19 UTC, husxk requested changes
Looks good. Change `scripts/` to `tools/`.
`scripts/` indicate that we store some scripts inside, however `scripts/gen_dist_data.cpp` is more like a tool for the project (same with the `norm_dist_plot.py` program).

Remember to squash commits.

2024-04-09 09:19 UTC, husxk commented on scripts/gen_dist_data.cpp
Instead of `//` all the lines, uncomment them and make this file a tool for the project.
You can make `tools/` directory and write small CMakeLists.txt and Makefile to automate generating these plots.

We would like to simply call 
`$ make` 
in the `tools/` directory and get the plots.

2024-04-17 10:39 UTC, husxk commented
Please change commit message

2024-04-17 11:19 UTC, husxk requested changes
Remember to squash commits and change commit message :]

2024-04-17 11:19 UTC, husxk commented on tools/Makefile
> +.PHONY: all ninja clean
add  `plots`, `dist_data`

2024-04-17 11:19 UTC, husxk commented on tools/Makefile
> +	cd build && gen_dist_data
shouldn't be just `./plots` ?

2024-04-17 11:19 UTC, husxk commented on tools/Makefile
> +	cd build && nmake
why not `cd build && ninja`?

2024-04-17 11:19 UTC, husxk commented on tools/Makefile
> +	cd build && python plots.py
`plots.py` is not in the `build/`

2024-04-17 11:19 UTC, husxk commented on tools/CMakeLists.txt
Have you tested if this cmake is working?

I had to do:
`
add_executable(${PROJECT_NAME}
        gen_dist_data.cpp
        ../mt_rng.cpp
)
`, in order to get correct linkage.

2024-04-18 09:46 UTC, husxk requested changes
remember to pull master and rebase your branch, yesterday I've merged other PR.

2024-04-18 09:46 UTC, husxk commented on tools/Makefile
> +	cd build && start gen_dist_data.exe
shouldn't be `cd build &&  ${RUN_CMD}`?

2024-04-23 13:00 UTC, closed without merging