Adding software implementing TEA
husxk/pwr-niduc-p pull request #4
Opened 2024-04-02 16:44 UTC by kornelu123

Instead of implementing RSA encryption algorithm, which is unpractical due to necessity of finding big prime numbers which is taking very long time I went with Tiny Encryption Algorithm, which do not have those flaws.

2024-04-03 20:20 UTC, kornelu123 commented
Mmmmm, what a beautiful piece of Object oriented programming ;]. :face_exhaling:

2024-04-09 09:06 UTC, husxk requested changes
It looks good, however can we break it to .h and .cpp files?
We can make `source/` and `include/` directories.
(You can add .h and .cpp file to your changes in one commit,
and restructure the project files in another one)
Do we want to leave `main.cpp`  in the main directory? What do you think?

Also, shouldn't we update CMakeLists.txt accordingly?

2024-04-09 09:06 UTC, husxk commented on tea.cpp
> +    }
Can't we just do
`tea_ctx_t(uint32_t* data, uint32_t u32_datasize)`?\
Then we do not need to calculate `u32_datasize`.

Also, then we can just do `std::memcpy(&(this->data), (void*)data, u32_datasize * 4);`

2024-04-09 09:06 UTC, husxk commented on tea.cpp
> +        printf("%08X", this->data[i]);
`printf("%08X ", this->data[i]);`?
The whitespace will make output more clear, no?
It's up to you whether change it or not.

2024-04-09 09:06 UTC, husxk commented on tea.cpp
> +    inline void
FYI: all functions here (class definition) are `inline` implicitly
([Inline explained at cppreference](https://en.cppreference.com/w/cpp/language/inline))

2024-04-09 12:08 UTC, kornelu123 commented
> It looks good, however can we break it to .h and .cpp files? 

Yeah we can, I'm not a fan of it but if You want then let's make it be.

> Also, shouldn't we update CMakeLists.txt accordingly?

Due to not having header file, just including .cpp file works.

> We can make `source/` and `include/` directories. (You can add .h and .cpp file to your changes in one commit, and restructure the project files in another one) Do we want to leave `main.cpp` in the main directory? What do you think?

TBH i think this is a small project, so we do not need the src/ and inc/ dirs. But it's your repo so I leave it up to you.

2024-04-09 12:10 UTC, kornelu123 commented on tea.cpp
> +    inline void
GTK, i think i would like to still explicitly write inline, what are your thoughts?

2024-04-09 21:13 UTC, husxk commented on tea.cpp
> +    inline void
I don't mind having it explicitly.

2024-04-09 21:15 UTC, husxk commented
> TBH i think this is a small project, so we do not need the src/ and inc/ dirs. But it's your repo so I leave it up to you.

I agree that it is a small project, so we can leave it as it is. If we get a ton of files, we will separate .cpp and .h

2024-04-17 11:24 UTC, husxk requested changes
Shouldn't we change CMakeLists.txt appropriately?

2024-04-17 11:24 UTC, husxk commented on main.cpp
> +#include "pattern_map.cpp"
there is no such a file

2024-04-17 11:24 UTC, husxk commented on main.cpp
> +#include "tea.cpp"
shouldn't we `#include "tea.hpp"`?

2024-04-17 12:27 UTC, husxk commented
Looks good, have you tested it?

2024-04-17 12:29 UTC, kornelu123 commented
yup

2024-04-17 12:41 UTC, merged